gripper_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint
  pid: { p: 0.0, i: 0.0, d: 0.0 }





shoulder_pan_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_pan_joint
  pid: {p: 4000,  d: 200, i: 1, i_clamp: 1}

shoulder_lift_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_lift_joint
  pid: {p: 10000,  d: 200, i: 1, i_clamp: 1}

elbow_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: elbow_joint
  pid: {p: 2000,  d: 20, i: 1, i_clamp: 1}

wrist_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_1_joint
  pid: {p: 500,  d: 1, i: 1, i_clamp: 1}

wrist_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_2_joint
  pid: {p: 500,  d: 1, i: 1, i_clamp: 1}

wrist_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_3_joint
  pid: {p: 10,  d: 0.1, i: 0, i_clamp: 1}


shoulder_pan_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: shoulder_pan_joint     # ajuste nome exato
  pid: { p: 0.0, i: 0.0, d: 0.0 }

shoulder_lift_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: shoulder_lift_joint     # ajuste nome exato
  pid: { p: 0.0, i: 0.0, d: 0.0 }

elbow_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: elbow_joint     # ajuste nome exato
  pid: { p: 0.0, i: 0.0, d: 0.0 }

wrist_1_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: elbow_joint     # ajuste nome exato
  pid: { p: 0.0, i: 0.0, d: 0.0 }

wrist_2_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: elbow_joint     # ajuste nome exato
  pid: { p: 0.0, i: 0.0, d: 0.0 }

wrist_3_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: elbow_joint     # ajuste nome exato
  pid: { p: 0.0, i: 0.0, d: 0.0 }



